import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { es } from '@/lib/i18n';

// English translations
export const en = {
  app: {
    name: 'CINEFORGE Studio',
    tagline: 'AI-powered cinema production',
  },
  nav: {
    dashboard: 'Dashboard',
    projects: 'Projects',
    dailies: 'Dailies',
    newProject: 'New Project',
    signOut: 'Sign Out',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    displayName: 'Display Name',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    createAccount: 'Create Account',
    welcomeBack: 'Welcome back',
    createYourAccount: 'Create your account',
  },
  dashboard: {
    title: 'Dashboard',
    subtitle: 'Welcome to your production studio',
    activeProjects: 'Active Projects',
    scenesRendered: 'Scenes Rendered',
    pendingQC: 'Pending QC',
    qcIssues: 'QC Issues',
    recentProjects: 'Recent Projects',
    viewAll: 'View all',
    createFirst: 'Create your first production',
    createFirstDesc: 'Start building a cinema-quality project with AI-powered tools, quality gates, and professional workflows.',
    quickActions: 'Quick Actions',
    importScript: 'Import Script',
    importScriptDesc: 'Upload a screenplay or paste text',
    reviewDailies: 'Review Dailies',
    reviewDailiesDesc: "Check today's renders and QC reports",
    sosAssistant: 'SOS Assistant',
    sosAssistantDesc: 'Get AI recommendations for your project',
    episodes: 'episodes',
    bible: 'Bible',
    ready: 'Ready',
    inProgress: 'In Progress',
  },
  projects: {
    title: 'Projects',
    subtitle: 'Manage your productions',
    newProject: 'New Project',
    search: 'Search projects...',
    noProjects: 'No projects yet',
    createFirst: 'Create your first project to get started',
    episodes: 'episodes',
    bible: 'Bible',
    format: {
      series: 'Series',
      mini: 'Mini-Series',
      film: 'Film',
    },
  },
  newProject: {
    title: 'New Project',
    subtitle: 'Create a new production',
    cancel: 'Cancel',
    steps: {
      basics: { title: 'Project Basics', description: 'Name and format' },
      episodes: { title: 'Episodes', description: 'Structure your content' },
      language: { title: 'Language', description: 'Master and targets' },
      budget: { title: 'Budget', description: 'Set cost limits' },
    },
    whatsCalled: "What's your project called?",
    memorableTitle: 'Give your production a memorable title',
    projectTitle: 'Project Title',
    titlePlaceholder: 'e.g., The Last Frontier',
    format: 'Format',
    recommended: 'Recommended',
    formatDesc: {
      series: 'Multi-episode with recurring characters',
      mini: 'Limited episodes with complete arc',
      film: 'Single long-form production',
    },
    structureContent: 'Structure your content',
    defineScope: 'Define the scope of your production',
    numberOfEpisodes: 'Number of Episodes',
    episodes: 'episodes',
    notSure: 'Not sure? Start with 6 episodes',
    targetDuration: 'Target Duration per',
    episode: 'Episode',
    film: 'Film',
    minutes: 'minutes',
    sosRecommendation: 'SOS Recommendation',
    forSeries: 'For a series format, 30-45 minute episodes allow for proper story development.',
    forMini: 'For a mini-series format, 30-45 minute episodes allow for proper story development.',
    forFilm: 'For a film format, 90-120 minutes is ideal for theatrical pacing.',
    languageSettings: 'Language settings',
    languageDesc: 'Choose your master language and localization targets',
    masterLanguage: 'Master Language',
    masterLanguageDesc: 'The primary language for dialogue and production',
    targetLanguages: 'Target Languages (Optional)',
    targetLanguagesDesc: 'Languages for dubbing and localization',
    budgetLimits: 'Budget limits (optional)',
    budgetDesc: 'Set spending caps to control costs',
    projectBudgetCap: 'Project Budget Cap',
    noLimit: 'No limit',
    reviewCreate: 'Review and create',
    reviewDesc: 'Confirm your project settings',
    projectSummary: 'Project Summary',
    back: 'Back',
    next: 'Next',
    create: 'Create Project',
    creating: 'Creating...',
  },
  projectTabs: {
    bible: 'Bible',
    stylePack: 'Style Pack',
    characters: 'Characters',
    locations: 'Locations',
    scriptImport: 'Script Import',
    scenes: 'Scenes',
    renderQueue: 'Render Queue',
    costEngine: 'Cost Engine',
    qcEngine: 'QC Engine',
    approvals: 'Approvals',
    team: 'Team',
    versions: 'Versions',
  },
  bible: {
    title: 'Production Bible',
    subtitle: 'Define your canon before generating content. Complete all sections to unlock rendering.',
    completeness: 'Bible Completeness',
    readyToProceed: 'Ready to proceed to script and rendering',
    sections: {
      style: { label: 'Style Pack', desc: 'Visual rules and references' },
      characters: { label: 'Characters', desc: 'character(s) defined' },
      locations: { label: 'Locations', desc: 'location(s) defined' },
    },
  },
  stylePack: {
    title: 'Style Pack',
    subtitle: 'Define the visual rules for your production',
    aspectRatio: 'Aspect Ratio',
    fps: 'Frames per Second',
    lensStyle: 'Lens Style',
    lensStylePlaceholder: 'e.g., Anamorphic, 35mm',
    filmGrain: 'Film Grain',
    save: 'Save Style Pack',
    saved: 'Style pack saved',
    saveFailed: 'Failed to save',
  },
  characters: {
    title: 'Characters',
    subtitle: 'Define your cast for continuity',
    addPlaceholder: 'Character name',
    add: 'Add',
    added: 'Character added',
    addFailed: 'Failed to add',
    noCharacters: 'No characters yet',
    noRole: 'No role defined',
    role: 'Role',
    bio: 'Biography',
    arc: 'Arc',
  },
  locations: {
    title: 'Locations',
    subtitle: 'Define your sets and environments',
    addPlaceholder: 'Location name',
    add: 'Add',
    added: 'Location added',
    addFailed: 'Failed to add',
    noLocations: 'No locations yet',
    noDescription: 'No description',
    description: 'Description',
    dayVariant: 'Day Variant',
    nightVariant: 'Night Variant',
  },
  scenes: {
    title: 'Scenes & Shots',
    subtitle: 'Plan your shots with quality modes and hero tagging',
    addScene: 'Add Scene',
    addShot: 'Add Shot',
    sluglinePlaceholder: 'INT. LOCATION - TIME',
    noScenes: 'No scenes yet. Add your first scene above.',
    shots: 'Shots',
    noShots: 'No shots yet',
    sosTip: 'SOS Tip',
    sosTipDesc: 'Mark key moments (close-ups, emotional beats, VFX) as HERO shots for higher quality rendering.',
    bibleRequired: 'Bible Required',
    bibleRequiredDesc: 'Complete your production bible (≥85%) to unlock scene management.',
    qualityModes: {
      CINE: '3 takes, QC ≥85%',
      ULTRA: '5 takes, QC ≥88%',
      HERO: 'Key shot, ULTRA mode',
    },
    episode: 'Episode',
  },
  scriptImport: {
    title: 'Script Import',
    subtitle: 'Paste your screenplay and let AI break it down into scenes',
    screenplayText: 'Screenplay Text',
    pasteDesc: 'Paste your screenplay in standard format. The AI will identify scenes, characters, and locations.',
    characters: 'characters',
    parseWithAI: 'Parse with AI',
    analyzing: 'Analyzing...',
    parsedScenes: 'Parsed Scenes',
    reviewBeforeImport: 'Review the extracted scenes before importing',
    importScenes: 'Import',
    importing: 'Importing...',
    scene: 'Scene',
    dialogueLines: 'dialogue lines',
    formatGuide: 'Script Format Guide',
    formatGuideDesc: 'For best results, use standard screenplay format',
    recommended: 'Recommended',
    aiDetection: 'AI Detection',
    foundScenes: 'Found scenes',
  },
  renderQueue: {
    title: 'Render Queue',
    subtitle: 'Monitor active renders, status, and costs',
    queued: 'Queued',
    running: 'Running',
    succeeded: 'Succeeded',
    failed: 'Failed',
    blocked: 'Blocked',
    totalCost: 'Total Cost',
    estimatedCost: 'Est. Cost',
    activeRenders: 'Active Renders',
    backgroundJobs: 'Background Jobs',
    noRenders: 'No renders in queue',
    noJobs: 'No background jobs',
    retry: 'Retry',
    cancel: 'Cancel',
    engine: 'Engine',
    take: 'Take',
  },
  costEngine: {
    title: 'Cost Engine',
    subtitle: 'Estimate production costs per scene',
    settings: 'Settings',
    low: 'Low',
    expected: 'Expected',
    high: 'High',
    cap: 'Cap',
    overBudget: 'Over Budget',
    overBudgetDesc: 'Expected cost exceeds budget cap. Consider reducing ULTRA scenes, limiting hero shots, or adjusting durations.',
    costAssumptions: 'Cost Assumptions',
    pricePerSecond: 'Price per Second',
    currency: 'Currency',
    padding: 'Padding (extra duration for montage)',
    cineRetryRates: 'CINE Retry Rates',
    ultraRetryRates: 'ULTRA Retry Rates',
    saveSettings: 'Save Settings',
    sceneBreakdown: 'Scene Breakdown',
    addScenesForEstimates: 'Add scenes with shots to see cost estimates',
    shots: 'shots',
    hero: 'hero',
  },
  qcEngine: {
    title: 'QC Engine',
    subtitle: 'Automated quality control for continuity, audio, and rhythm',
    runQCCheck: 'Run QC Check',
    analyzing: 'Analyzing...',
    exportBlocked: 'Export Blocked',
    exportReady: 'Export Ready',
    exportBlockedDesc: 'is below CINE threshold',
    exportReadyDesc: 'Quality standards met - ready for export',
    exportProject: 'Export Project',
    overallScore: 'Overall QC Score',
    continuity: 'Continuity',
    continuityDesc: 'Character consistency, location matching, props continuity',
    audio: 'Audio',
    audioDesc: 'Dialogue sync, ambient sound, music timing',
    rhythm: 'Rhythm',
    rhythmDesc: 'Pacing, edit timing, scene flow',
    recentIssues: 'Recent Issues',
    issuesDesc: 'Issues detected in the latest QC analysis',
    noIssues: 'No issues detected',
    qualityThresholds: 'Quality Mode Thresholds',
    thresholdsDesc: 'Minimum scores required for each quality tier',
    standardProduction: 'Standard production',
    premiumQuality: 'Premium quality',
    trailerReady: 'Trailer-ready',
    checks: {
      characterAppearance: 'Character appearance',
      costumeConsistency: 'Costume consistency',
      propPlacement: 'Prop placement',
      locationMatching: 'Location matching',
      lipSync: 'Lip sync accuracy',
      ambientLevels: 'Ambient levels',
      musicCues: 'Music cues',
      soundEffects: 'Sound effects',
      shotPacing: 'Shot pacing',
      cutTiming: 'Cut timing',
      sceneTransitions: 'Scene transitions',
      emotionalBeats: 'Emotional beats',
    },
  },
  approvals: {
    title: 'Approval Workflow',
    subtitle: 'Review and approve scenes and shots before rendering',
    totalItems: 'Total Items',
    pendingReview: 'Pending Review',
    approved: 'Approved',
    needsRevision: 'Needs Revision',
    scenes: 'Scenes',
    shots: 'Shots',
    noScenes: 'No scenes to review',
    noShots: 'No shots to review',
    workflow: 'Approval Workflow',
    workflowDesc: 'How content moves through review',
    awaitingReview: 'Awaiting review',
    readyForRender: 'Ready for render',
  },
  team: {
    title: 'Team Members',
    subtitle: 'Manage who has access to the project and their permissions',
    inviteMember: 'Invite Member',
    projectOwner: 'Project Owner',
    fullControl: 'Full control over all settings',
    noMembers: 'No team members yet',
    inviteCollaborators: 'Invite collaborators to work on this project',
    emailOrUsername: 'Email or username',
    role: 'Role',
    permissions: 'Permissions',
    sendInvite: 'Send Invite',
    inviting: 'Inviting...',
    invited: 'Member invited successfully',
    inviteFailed: 'Failed to invite',
    roleUpdated: 'Role updated',
    memberRemoved: 'Member removed',
    rolesReference: 'Roles Reference',
    whatEachRoleCan: 'What each role can do in your project',
    roles: {
      owner: 'Owner',
      producer: 'Producer',
      director: 'Director',
      writer: 'Writer',
      dp: 'Director of Photography',
      sound: 'Sound',
      reviewer: 'Reviewer',
    },
    rolePermissions: {
      owner: ['All permissions', 'Delete project', 'Manage members'],
      producer: ['Manage budget', 'Approve scenes', 'Manage schedules'],
      director: ['Approve shots', 'Manage scenes', 'Review dailies'],
      writer: ['Edit scripts', 'Manage characters', 'Edit dialogue'],
      dp: ['Manage camera', 'Configure lighting', 'Shot composition'],
      sound: ['Audio review', 'Sound design', 'Music cues'],
      reviewer: ['View project', 'Add comments', 'Review dailies'],
    },
  },
  dailies: {
    title: 'Dailies Review',
    subtitle: 'Review and approve renders',
    createDemoSession: 'Create Demo Session',
    sessions: 'Sessions',
    noSessions: 'No sessions yet',
    noRenders: 'No renders to review',
    noRendersDesc: 'Create scenes and generate renders to start reviewing dailies.',
    scene: 'Scene',
    shot: 'Shot',
    take: 'Take',
    of: 'of',
    select: 'Select',
    fix: 'Fix',
    reject: 'Reject',
    addFrameNote: 'Add frame note (e.g., 00:03 - audio pop)',
    acting: 'Acting',
    camera: 'Camera',
    lighting: 'Lighting',
    sound: 'Sound',
    feelsReal: 'Feels Real',
    markedAs: 'Marked as',
  },
  versionHistory: {
    title: 'Version History',
    versions: 'versions',
    saveVersion: 'Save Version',
    noVersions: 'No versions saved',
    saveInitial: 'Save Initial Version',
    version: 'Version',
    noDescription: 'No description',
    compare: 'Compare with',
    rollback: 'Rollback to this version',
    rollingBack: 'Rolling back...',
    comparing: 'Comparing Versions',
    added: 'added',
    removed: 'removed',
    changed: 'changed',
    noDifferences: 'No differences',
  },
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    loading: 'Loading...',
    saving: 'Saving...',
    success: 'Success',
    error: 'Error',
    confirm: 'Confirm',
    search: 'Search',
    filter: 'Filter',
    all: 'All',
    none: 'None',
    yes: 'Yes',
    no: 'No',
    or: 'or',
    and: 'and',
  },
  errors: {
    generic: 'An error occurred',
    notFound: 'Not found',
    unauthorized: 'Unauthorized',
    rateLimited: 'Too many requests. Please try again later.',
    paymentRequired: 'Credits exhausted. Add more to continue.',
  },
  language: {
    select: 'Language',
    es: 'Español',
    en: 'English',
  },
};

export type Translations = typeof en;
export type Language = 'es' | 'en';

const translations: Record<Language, Translations> = { en, es: es as unknown as Translations };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('cineforge-language');
    return (saved as Language) || 'es';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('cineforge-language', lang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
