-- Add profile_json column to locations table for storing entity-builder generated profiles
ALTER TABLE public.locations 
ADD COLUMN IF NOT EXISTS profile_json JSONB;

COMMENT ON COLUMN public.locations.profile_json IS 
'Visual profile generated by entity-builder for rich prompt construction';